### ISSUE TITLE
Diving helmet server crash

### ISSUE THREAD

**Issue by Proxwian** [Robocraft999/CreatePlus#27]
If player somehow gets diving helmet, dedicated server crashes

Minecraft 1.18.2
Forge 40.1.71

```
Time: 8/31/22, 6:38 PM
Description: Exception in server tick loop

java.lang.NoSuchFieldError: DIVING_HELMET
	at com.robocraft999.createplus.item.crafting.GHelmetCrafingRecipe.assemble(GHelmetCrafingRecipe.java:62) ~[createplus-1.18.2_v0.5.1.jar%2395!/:1.18.2_v0.5.1] {re:classloading}
	at com.robocraft999.createplus.item.crafting.GHelmetCrafingRecipe.m_5874_(GHelmetCrafingRecipe.java:28) ~[createplus-1.18.2_v0.5.1.jar%2395!/:1.18.2_v0.5.1] {re:classloading}
	at top.theillusivec4.polymorph.common.integration.fastbench.FastBenchModule.selectRecipe(FastBenchModule.java:63) ~[polymorph-forge-1.18.2-0.44.jar%23225!/:task ':jar' property 'archiveVersion'] {re:classloading}
	at top.theillusivec4.polymorph.common.network.client.CPacketPlayerRecipeSelection.lambda$handle$1(CPacketPlayerRecipeSelection.java:64) ~[polymorph-forge-1.18.2-0.44.jar%23225!/:task ':jar' property 'archiveVersion'] {re:classloading}
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}
	at top.theillusivec4.polymorph.common.network.client.CPacketPlayerRecipeSelection.lambda$handle$2(CPacketPlayerRecipeSelection.java:58) ~[polymorph-forge-1.18.2-0.44.jar%23225!/:task ':jar' property 'archiveVersion'] {re:classloading}
	at net.minecraftforge.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:213) ~[forge-1.18.2-40.1.73-universal.jar%23290!/:?] {re:classloading}
	at top.theillusivec4.polymorph.common.network.client.CPacketPlayerRecipeSelection.handle(CPacketPlayerRecipeSelection.java:53) ~[polymorph-forge-1.18.2-0.44.jar%23225!/:task ':jar' property 'archiveVersion'] {re:classloading}
	at net.minecraftforge.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:115) ~[forge-1.18.2-40.1.73-universal.jar%23290!/:?] {re:classloading}
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}
	at net.minecraftforge.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:115) ~[forge-1.18.2-40.1.73-universal.jar%23290!/:?] {re:classloading}
	at net.minecraftforge.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:153) ~[forge-1.18.2-40.1.73-universal.jar%23290!/:?] {re:classloading}
	at net.minecraftforge.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:72) ~[forge-1.18.2-40.1.73-universal.jar%23290!/:?] {re:mixin,re:classloading,pl:mixin:APP:connectivity.mixins.json:SimpleChannelMixin,pl:mixin:A}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.network.NetworkInstance.dispatch(NetworkInstance.java:68) ~[forge-1.18.2-40.1.73-universal.jar%23290!/:?] {re:classloading}
	at net.minecraftforge.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:78) ~[forge-1.18.2-40.1.73-universal.jar%23290!/:?] {re:classloading}
	at java.util.Optional.map(Optional.java:260) ~[?:?] {re:mixin}
	at net.minecraftforge.network.NetworkHooks.onCustomPayload(NetworkHooks.java:78) ~[forge-1.18.2-40.1.73-universal.jar%23290!/:?] {re:classloading}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7423_(ServerGamePacketListenerImpl.java:1439) ~[server-1.18.2-20220404.173914-srg.jar%23285!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.m_5797_(ServerboundCustomPayloadPacket.java:35) ~[server-1.18.2-20220404.173914-srg.jar%23285!/:?] {re:mixin,re:classloading,pl:mixin:APP:connectivity.mixins.json:networkstats.CCustomPayloadPacketNameMixin,pl:mixin:A}
	at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.m_5797_(ServerboundCustomPayloadPacket.java:8) ~[server-1.18.2-20220404.173914-srg.jar%23285!/:?] {re:mixin,re:classloading,pl:mixin:APP:connectivity.mixins.json:networkstats.CCustomPayloadPacketNameMixin,pl:mixin:A}
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[server-1.18.2-20220404.173914-srg.jar%23285!/:?] {re:classloading}
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.18.2-20220404.173914-srg.jar%23285!/:?] {re:classloading,re:mixin}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[server-1.18.2-20220404.173914-srg.jar%23285!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.18.2-20220404.173914-srg.jar%23285!/:?] {re:computing_frames,re:mixin,re:classloading}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:799) ~[server-1.18.2-20220404.173914-srg.jar%23285!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:flytre_lib.mixins.json:base.MinecraftServerMixin,pl:mixin:APP:flytre_lib.mixins.json:config.MinecraftServerMixin,pl:mixin:APP:mobifier.mixins.json:MixinMinecraftServer,pl:mixin:APP:fastload.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:unionlib.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:164) ~[server-1.18.2-20220404.173914-srg.jar%23285!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:flytre_lib.mixins.json:base.MinecraftServerMixin,pl:mixin:APP:flytre_lib.mixins.json:config.MinecraftServerMixin,pl:mixin:APP:mobifier.mixins.json:MixinMinecraftServer,pl:mixin:APP:fastload.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:unionlib.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[server-1.18.2-20220404.173914-srg.jar%23285!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:782) ~[server-1.18.2-20220404.173914-srg.jar%23285!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:flytre_lib.mixins.json:base.MinecraftServerMixin,pl:mixin:APP:flytre_lib.mixins.json:config.MinecraftServerMixin,pl:mixin:APP:mobifier.mixins.json:MixinMinecraftServer,pl:mixin:APP:fastload.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:unionlib.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:776) ~[server-1.18.2-20220404.173914-srg.jar%23285!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:flytre_lib.mixins.json:base.MinecraftServerMixin,pl:mixin:APP:flytre_lib.mixins.json:config.MinecraftServerMixin,pl:mixin:APP:mobifier.mixins.json:MixinMinecraftServer,pl:mixin:APP:fastload.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:unionlib.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116) ~[server-1.18.2-20220404.173914-srg.jar%23285!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:761) ~[server-1.18.2-20220404.173914-srg.jar%23285!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:flytre_lib.mixins.json:base.MinecraftServerMixin,pl:mixin:APP:flytre_lib.mixins.json:config.MinecraftServerMixin,pl:mixin:APP:mobifier.mixins.json:MixinMinecraftServer,pl:mixin:APP:fastload.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:unionlib.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:689) ~[server-1.18.2-20220404.173914-srg.jar%23285!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:flytre_lib.mixins.json:base.MinecraftServerMixin,pl:mixin:APP:flytre_lib.mixins.json:config.MinecraftServerMixin,pl:mixin:APP:mobifier.mixins.json:MixinMinecraftServer,pl:mixin:APP:fastload.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:unionlib.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[server-1.18.2-20220404.173914-srg.jar%23285!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:flytre_lib.mixins.json:base.MinecraftServerMixin,pl:mixin:APP:flytre_lib.mixins.json:config.MinecraftServerMixin,pl:mixin:APP:mobifier.mixins.json:MixinMinecraftServer,pl:mixin:APP:fastload.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:unionlib.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}
```

**Comment by Proxwian** [comment]
Upd: looks like if you take any other helmet from mod, it'll crash

**Comment by Proxwian** [comment]
Update: crash if you see helmet craft
