### ISSUE TITLE
Rendering exception thrown when hovering over any CreatePlus items

### ISSUE THREAD

**Issue by AdaptiveEmpath** [Robocraft999/CreatePlus#33]
[31Jan2023 00:02:20.209] [Render thread/ERROR] [net.minecraft.client.Minecraft/FATAL]: Reported exception thrown!
net.minecraft.ReportedException: Rendering screen
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:909) ~[client-1.19.2-20220805.130853-srg.jar%23719!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1115) ~[client-1.19.2-20220805.130853-srg.jar%23719!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23719!/:?]
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23719!/:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23719!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.3.jar%2395!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
Caused by: java.lang.NullPointerException: Registry Object not present: createplus:goggle_unit
	at java.util.Objects.requireNonNull(Unknown Source) ~[?:?]
	at net.minecraftforge.registries.RegistryObject.get(RegistryObject.java:204) ~[forge-1.19.2-43.2.3-universal.jar%23724!/:?]
	at com.robocraft999.createplus.item.goggle.GoggleArmor.isGoggleHelmet(GoggleArmor.java:67) ~[createplus-1.19.2_v0.5.3-beta.jar%23498!/:1.19.2_v0.5.3-beta]
	at com.simibubi.create.content.contraptions.goggles.GogglesItem.isWearingGoggles(GogglesItem.java:53) ~[create-1.19.2-0.5.0.h.jar%23496!/:0.5.0.h]
	at com.simibubi.create.foundation.item.TooltipHelper.hasTooltip(TooltipHelper.java:236) ~[create-1.19.2-0.5.0.h.jar%23496!/:0.5.0.h]
	at com.simibubi.create.events.ClientEvents.addToItemTooltip(ClientEvents.java:261) ~[create-1.19.2-0.5.0.h.jar%23496!/:0.5.0.h]
	at com.simibubi.create.events.__ClientEvents_addToItemTooltip_ItemTooltipEvent.invoke(.dynamic) ~[create-1.19.2-0.5.0.h.jar%23496!/:0.5.0.h]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2379!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2379!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2379!/:?]
	at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:257) ~[forge-1.19.2-43.2.3-universal.jar%23724!/:?]
	at net.minecraft.world.item.ItemStack.m_41651_(ItemStack.java:782) ~[client-1.19.2-20220805.130853-srg.jar%23719!/:?]
	at net.minecraft.client.gui.screens.Screen.m_96555_(Screen.java:193) ~[client-1.19.2-20220805.130853-srg.jar%23719!/:?]
	at net.minecraft.client.gui.screens.Screen.m_6057_(Screen.java:170) ~[client-1.19.2-20220805.130853-srg.jar%23719!/:?]
	at net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.m_7025_(AbstractContainerScreen.java:173) ~[client-1.19.2-20220805.130853-srg.jar%23719!/:?]
	at net.minecraft.client.gui.screens.inventory.InventoryScreen.m_6305_(InventoryScreen.java:84) ~[client-1.19.2-20220805.130853-srg.jar%23719!/:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:440) ~[forge-1.19.2-43.2.3-universal.jar%23724!/:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:433) ~[forge-1.19.2-43.2.3-universal.jar%23724!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:896) ~[client-1.19.2-20220805.130853-srg.jar%23719!/:?]
	... 17 more

**Comment by Robocraft999** [comment]
Do you have Mekanism installed?

**Comment by AdaptiveEmpath** [comment]
Yeah, here is the mod list if that helps: https://www.feed-the-beast.com/modpacks/101-ftb-presents-direwolf20-119

**Comment by AdaptiveEmpath** [comment]
I am now realizing that there is probably some sort of initialization exception prior to this that is causing the exception. I'll try and look in the logs to see if this is the case. You'd think that if create_plus was failing to initialize that the constructors adding the `isWearingPredicates` wouldn't get added and we would not see the issue in the first place. I don't know how forge works though so 🤷
